const fs = require("fs");
const got = require("got");

module.exports = {
  config: {
    name: "shh",                 
    version: "1.0.1",
    author: "Redwan (Xe Mo)",
    description: "Umm Wanna Do Shh? ",
    category: "Utility", 
    cooldown: 2
  },
  
  onStart: async function ({ api, event }) {
    const link = [
      "https://i.postimg.cc/L4W1grR4/f61965dd79bfa2e1fbae50.jpg",
      "https://i.postimg.cc/GpYFpmrp/d08bd620516e8b30d27f7.jpg",
      "https://i.postimg.cc/SNT7TPDm/597f1db299fc43a21aed76.jpg",
      "https://i.postimg.cc/9QsPVq6S/d10b902a1464ce3a9775130.jpg",
      "https://i.postimg.cc/VkJ93FVn/ff4e057a81345b6a0225139.jpg",
      "https://i.imgur.com/2SKrp2u.jpg",
      "https://i.imgur.com/OlbhP3I.jpg",
      "https://i.imgur.com/tv8YAqH.jpg",
      "https://i.imgur.com/ck9lOWc.jpg",
      "https://i.imgur.com/YfIrxAo.jpg",
      "https://i.imgur.com/Zjzx5LB.jpg",
      "https://i.imgur.com/I7Gkerg.jpg",
      "https://i.imgur.com/GRoq1bw.jpg",
      "https://i.imgur.com/RkrvTXD.jpg",
      "https://i.imgur.com/dpm9YSJ.jpg",
      "https://i.imgur.com/dbTFwnL.jpg",
      "https://i.imgur.com/NniVjSX.jpg",
      "https://i.imgur.com/sPTDj7J.jpg",
      "https://i.imgur.com/eKO5bbW.jpg",
      "https://i.imgur.com/e8Hs2LK.jpg",
      "https://i.imgur.com/JB9Ma7r.jpg",
      "https://i.imgur.com/skZasjw.jpg",
      "https://i.imgur.com/uzlkEbQ.jpg",
      "https://i.imgur.com/etPLICr.jpg",
      "https://i.imgur.com/qDCx7ZN.jpg",
      "https://i.imgur.com/9pcXEs7.jpg",
      "https://i.imgur.com/UgcqVy6.jpg",
      "https://i.imgur.com/87tIKH3.jpg",
      "https://i.imgur.com/ISLIYWY.jpg",
      "https://i.imgur.com/MWzaNIp.jpg",
      "https://i.imgur.com/phQvE2O.jpg",
      "https://i.imgur.com/rWn34JA.jpg",
      "https://i.imgur.com/EazwRhR.jpg",
      "https://i.imgur.com/KDMhunJ.jpg",
      "https://i.imgur.com/08RUzA6.jpg",
      "https://i.imgur.com/kpFhb0p.jpg",
      "https://i.imgur.com/Ap5k1pG.jpg",
      "https://i.imgur.com/hPqyBrA.jpg",
      "https://i.imgur.com/giLgkEc.jpg",
      "https://i.imgur.com/YENMRSS.jpg",
      "https://i.imgur.com/WJLKBbf.jpg",
      "https://i.imgur.com/7Whaezd.jpg",
      "https://i.imgur.com/8w3EYPR.jpg",
      "https://i.imgur.com/47dMIkP.jpg",
      "https://i.imgur.com/tDfrVtL.jpg",
      "https://i.imgur.com/CA6ArRA.jpg",
      "https://i.imgur.com/nLrLI5a.jpg",
      "https://i.imgur.com/dw3BhAm.jpg",
      "https://i.imgur.com/pC2aXuC.jpg",
      "https://i.imgur.com/YP28MO8.jpg",
      "https://i.imgur.com/KFwCJys.jpg",
      "https://i.imgur.com/ArLIBjf.jpg",
      "https://i.imgur.com/6CVZ99N.jpg",
      "https://i.imgur.com/8j6zktC.jpg",
      "https://i.imgur.com/J9bRu0G.jpg",
      "https://i.imgur.com/HZOBVcd.jpg",
      "https://i.imgur.com/MoozhQ4.jpg",
      "https://i.imgur.com/D7SErWN.jpg",
      "https://i.imgur.com/Y92A06z.jpg",
      "https://i.imgur.com/t1nXKRE.jpg",
      "https://i.imgur.com/G4ZkJgb.jpg",
      "https://i.imgur.com/KDrZUTI.jpg",
      "https://i.imgur.com/BIGAkv6.jpg",
      "https://i.imgur.com/jzd9SOz.jpg",
      "https://i.imgur.com/ZP8Rt6X.jpg",
      "https://i.imgur.com/QlakQZO.jpg",
      "https://i.imgur.com/oa9mUMc.jpg",
      "https://i.imgur.com/CaaGAlS.jpg",
      "https://i.imgur.com/myWiaZq.jpg",
      "https://i.imgur.com/SU3Ahjv.jpg",
      "https://i.imgur.com/gpFOq8u.jpg",
      "https://i.imgur.com/8djscvM.jpg",
      "https://i.imgur.com/UUTCTH8.jpg",
      "https://i.imgur.com/IBfQmpC.jpg",
      "https://i.imgur.com/ZYBotms.jpg",
      "https://i.imgur.com/PKXpOLt.jpg",
      "https://i.imgur.com/Fbmn8pJ.jpg",
      "https://i.imgur.com/COqwBC1.jpg",
      "https://i.imgur.com/H3AvmJf.jpg",
      "https://i.imgur.com/EWIwuLd.jpg",
      "https://i.imgur.com/6jwc14e.jpg",
      "https://i.imgur.com/P6ZeoXS.jpg",
      "https://i.imgur.com/XuLiXEn.jpg",
      "https://i.imgur.com/PePdM8G.jpg",
      "https://i.imgur.com/GFlJZrX.jpg",
      "https://i.imgur.com/xGTYbOn.jpg",
      "https://i.imgur.com/zvSZRzy.jpg",
      "https://i.imgur.com/Ryu6QWZ.jpg",
      "https://i.imgur.com/c1jWpDB.jpg",
      "https://i.imgur.com/UE8usdY.jpg",
      "https://i.imgur.com/kNi5OwZ.jpg",
      "https://i.imgur.com/4zqMGJM.jpg",
      "https://i.imgur.com/h3EJCxZ.jpg",
      "https://i.imgur.com/5Utsv72.jpg",
      "https://i.imgur.com/2bxwpSN.jpg",
      "https://i.imgur.com/GIgsDE7.jpg",
      "https://i.imgur.com/ELw4MXY.jpg",
      "https://i.imgur.com/6RNNMsS.jpg",
      "https://i.imgur.com/zB86OHv.jpg",
      "https://i.imgur.com/aLMebPV.jpg",
      "https://i.imgur.com/b4vmkJc.jpg",
      "https://i.imgur.com/16CDKNK.jpg",
      "https://i.imgur.com/h1VBTPR.jpg",
      "https://i.imgur.com/YChnU4J.jpg",
      "https://i.imgur.com/oMqh9tK.jpg",
      "https://i.imgur.com/oQvLuRQ.jpg",
      "https://i.imgur.com/kGDQlEo.jpg",
      "https://i.imgur.com/Z5Ss9PX.jpg",
      "https://i.imgur.com/zp7aeRK.jpg",
      "https://i.imgur.com/fk0NwMN.jpg",
      "https://i.imgur.com/HIj5GcF.jpg",
      "https://i.imgur.com/QSACPLy.jpg",
      "https://i.imgur.com/7U2V2jM.jpg",
      "https://i.imgur.com/pwwCcFh.jpg",
      "https://i.imgur.com/ig1aqOp.jpg",
      "https://i.imgur.com/JQOU5F3.jpg",
      "https://i.imgur.com/18hfC7q.jpg",
      "https://i.imgur.com/X1JzQpd.jpg",
      "https://i.imgur.com/Xak0cS8.jpg",
      "https://i.imgur.com/KBNHQwK.jpg",
      "https://i.imgur.com/UnqYXdZ.jpg",
      "https://i.imgur.com/eMbGZ4t.jpg",
      "https://i.imgur.com/LVkwzaJ.jpg",
      "https://i.imgur.com/TyM0dUS.jpg",
      "https://i.imgur.com/aPpMYin.jpg",
      "https://i.imgur.com/KPGE405.jpg",
      "https://i.imgur.com/rpGR5bx.jpg",
      "https://i.imgur.com/71wOpEu.jpg",
      "https://i.imgur.com/e2xuLjB.jpg",
      "https://i.imgur.com/7jaK4D2.jpg",
      "https://i.imgur.com/IT8yhUM.jpg",
      "https://i.imgur.com/6zg0uxN.jpg",
      "https://i.imgur.com/w7KAi99.jpg",
      "https://i.imgur.com/A1dtgTQ.jpg",
      "https://i.imgur.com/geL27rv.jpg",
      "https://i.imgur.com/D73XkSb.jpg",
      "https://i.imgur.com/va0ms79.jpg",
      "https://i.imgur.com/Pye2LvP.jpg",
      "https://i.imgur.com/KuF7iNW.jpg",
      "https://i.imgur.com/Jg197E5.jpg",
      "https://i.imgur.com/m49l3uE.jpg",
      "https://i.imgur.com/oqeYvrw.jpg"
    ];

    const imgPath = __dirname + "/cache/gai.jpg";
    const randomImg = link[Math.floor(Math.random() * link.length)];

    try {
      const response = await got(randomImg, { responseType: "buffer" });
      fs.writeFileSync(imgPath, response.body);

      api.sendMessage(
        { body: "let's shhh ✨", attachment: fs.createReadStream(imgPath) },
        event.threadID,
        () => fs.unlinkSync(imgPath)
      );
    } catch (e) {
      console.error(e);
      api.sendMessage("💔🥀.", event.threadID);
    }
  }
};
